[build]
  command = "pip install -r requirements.txt"
  functions = "netlify_functions"
  publish = "."

[dev]
  command = "python app.py"
  port = 5000

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/mapa"
  to = "/.netlify/functions/api/mapa"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200