services:
  - type: web
    name: gps-rutas-seguras
    runtime: python
    repo: https://github.com/Mirandateresa/GPSrutas.git
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_MAPS_API_KEY
        value: AIzaSyBI7-JK1Ll0OQGwG7n0tTdkQAYRDN4f094  # ← TU CLAVE AQUÍ
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000